spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/book
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  profiles:
    include: oauth

logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.type: trace
